# TCL File Generated by Component Editor 13.1
# Fri May 16 16:05:01 MYT 2014
# DO NOT MODIFY


# 
# axi_conduit_merger "axi_conduit_merger" v1.0
# Altera 2014.05.16.16:05:01
# 
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module axi_conduit_merger
# 
set_module_property DESCRIPTION "This component allow manual modification of AXI control bus signals (AxCache, AxUser, and AxProt) via externally exported conduit"
set_module_property NAME axi_conduit_merger
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Interconnect"
set_module_property AUTHOR "Altera Corporation"
set_module_property DISPLAY_NAME "Altera AXI and Conduit Merger"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
#set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property ELABORATION_CALLBACK elaborate
set_module_property VALIDATION_CALLBACK validate
# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL axi_conduit_merger
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file axi_conduit_merger.v VERILOG PATH ./axi_conduit_merger.v TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL axi_conduit_merger
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file axi_conduit_merger.v VERILOG PATH ./axi_conduit_merger.v

add_fileset SIM_VHDL SIM_VHDL sim_callback_procedure_vhdl
set_fileset_property SIM_VHDL TOP_LEVEL axi_conduit_merger
set_fileset_property SIM_VHDL ENABLE_RELATIVE_INCLUDE_PATHS false

proc sim_callback_procedure_vhdl { entity_name } {
   if {__ACDS_HAS_MENTOR_ENCRYPTION__} { 
      add_fileset_file mentor/axi_conduit_merger.v SYSTEM_VERILOG_ENCRYPT PATH "mentor/axi_conduit_merger.v" {MENTOR_SPECIFIC}}

   add_fileset_file axi_conduit_merger.v SYSTEM_VERILOG PATH "./axi_conduit_merger.v" {{ALDEC_SPECIFIC} {CADENCE_SPECIFIC} {SYNOPSYS_SPECIFIC}}
   }

# 
# parameters
# 
add_parameter 		    ID_WIDTH	INTEGER 		8
set_parameter_property 	ID_WIDTH	ALLOWED_RANGES  1:32
set_parameter_property 	ID_WIDTH	DISPLAY_NAME	"Transaction ID Width"
set_parameter_property 	ID_WIDTH	TYPE 			INTEGER
set_parameter_property 	ID_WIDTH	UNITS 			None
set_parameter_property 	ID_WIDTH	HDL_PARAMETER 	true
set_parameter_property 	ID_WIDTH	AFFECTS_GENERATION false
set_parameter_property  ID_WIDTH	ENABLED 		true
#set_parameter_property  ID_WIDTH	GROUP  			"AXI bus signals for modification via conduit"

add_parameter 		    DATA_WIDTH	INTEGER 		32
set_parameter_property 	DATA_WIDTH	ALLOWED_RANGES  1:1024
set_parameter_property 	DATA_WIDTH	DISPLAY_NAME	"Data Width"
set_parameter_property 	DATA_WIDTH	TYPE 			INTEGER
set_parameter_property 	DATA_WIDTH	UNITS 			None
set_parameter_property 	DATA_WIDTH	HDL_PARAMETER 	true
set_parameter_property 	DATA_WIDTH	AFFECTS_GENERATION false
set_parameter_property  DATA_WIDTH	ENABLED 		true

add_parameter 			ADDRESS_WIDTH INTEGER 32
set_parameter_property 	ADDRESS_WIDTH AFFECTS_GENERATION false
set_parameter_property 	ADDRESS_WIDTH DERIVED true
set_parameter_property 	ADDRESS_WIDTH HDL_PARAMETER true
set_parameter_property 	ADDRESS_WIDTH AFFECTS_ELABORATION true
set_parameter_property 	ADDRESS_WIDTH VISIBLE false
set_parameter_property 	ADDRESS_WIDTH SYSTEM_INFO {ADDRESS_WIDTH altera_axi_master}

add_parameter 		    AXCACHE_EN		INTEGER 		0
set_parameter_property 	AXCACHE_EN		DISPLAY_NAME	"AxCache Signals"
set_parameter_property 	AXCACHE_EN		DISPLAY_HINT 	"boolean"
set_parameter_property 	AXCACHE_EN		UNITS 			None
set_parameter_property 	AXCACHE_EN		VISIBLE  	 	false
set_parameter_property 	AXCACHE_EN		HDL_PARAMETER 	false
set_parameter_property 	AXCACHE_EN		AFFECTS_GENERATION false
set_parameter_property  AXCACHE_EN		ENABLED  		true
set_parameter_property  AXCACHE_EN		GROUP  			"AXI bus signals for modification via conduit"
 
add_parameter 		    AXPROT_EN		INTEGER 		0
set_parameter_property 	AXPROT_EN		DISPLAY_NAME	"AxProt Signals"
set_parameter_property 	AXPROT_EN		DISPLAY_HINT 	"boolean"
set_parameter_property 	AXPROT_EN		UNITS 			None
set_parameter_property 	AXPROT_EN		VISIBLE		 	false
set_parameter_property 	AXPROT_EN		HDL_PARAMETER 	false
set_parameter_property 	AXPROT_EN		AFFECTS_GENERATION false
set_parameter_property  AXPROT_EN		ENABLED  		true
set_parameter_property  AXPROT_EN		GROUP  			"AXI bus signals for modification via conduit"
 
add_parameter 		    AXUSER_EN		INTEGER 		0
set_parameter_property 	AXUSER_EN		DISPLAY_NAME	"AxUser Signals"
set_parameter_property 	AXUSER_EN		DISPLAY_HINT 	"boolean"
set_parameter_property 	AXUSER_EN		UNITS 			None
set_parameter_property 	AXUSER_EN		VISIBLE		 	false
set_parameter_property 	AXUSER_EN		HDL_PARAMETER 	false
set_parameter_property 	AXUSER_EN		AFFECTS_GENERATION false
set_parameter_property  AXUSER_EN		ENABLED  		true
set_parameter_property  AXUSER_EN		GROUP  			"AXI bus signals for modification via conduit"
 
add_parameter 		    AXUSER_WIDTH	INTEGER 		5
set_parameter_property 	AXUSER_WIDTH	ALLOWED_RANGES  1:32
set_parameter_property 	AXUSER_WIDTH	DISPLAY_NAME	"AxUser Width"
set_parameter_property 	AXUSER_WIDTH	TYPE 			INTEGER
set_parameter_property 	AXUSER_WIDTH	UNITS 			None
set_parameter_property 	AXUSER_WIDTH	VISIBLE		 	false
set_parameter_property 	AXUSER_WIDTH	HDL_PARAMETER 	true
set_parameter_property 	AXUSER_WIDTH	AFFECTS_GENERATION false
set_parameter_property  AXUSER_WIDTH	ENABLED false
set_parameter_property  AXUSER_WIDTH	GROUP  			"AXI bus signals for modification via conduit"

add_parameter 		    WUSER_EN		INTEGER 		0
set_parameter_property 	WUSER_EN		DISPLAY_NAME	"WUser Signals"
set_parameter_property 	WUSER_EN		DISPLAY_HINT 	"boolean"
set_parameter_property 	WUSER_EN		UNITS 			None
set_parameter_property 	WUSER_EN		VISIBLE		 	false
set_parameter_property 	WUSER_EN		HDL_PARAMETER 	false
set_parameter_property 	WUSER_EN		AFFECTS_GENERATION false
set_parameter_property  WUSER_EN		ENABLED  		true
set_parameter_property  WUSER_EN		GROUP  			"AXI bus signals for modification via conduit"

add_parameter 		    WUSER_WIDTH		INTEGER 		5
set_parameter_property 	WUSER_WIDTH		ALLOWED_RANGES  1:32
set_parameter_property 	WUSER_WIDTH		DISPLAY_NAME	"WUSER Width"
set_parameter_property 	WUSER_WIDTH		TYPE 			INTEGER
set_parameter_property 	WUSER_WIDTH		UNITS 			None
set_parameter_property 	WUSER_WIDTH		VISIBLE		 	false
set_parameter_property 	WUSER_WIDTH		HDL_PARAMETER 	false
set_parameter_property 	WUSER_WIDTH		AFFECTS_GENERATION false
set_parameter_property  WUSER_WIDTH		ENABLED false
set_parameter_property  WUSER_WIDTH		GROUP  			"AXI bus signals for modification via conduit"

add_parameter 		    RUSER_EN		INTEGER 		0
set_parameter_property 	RUSER_EN		DISPLAY_NAME	"RUser Signals"
set_parameter_property 	RUSER_EN		DISPLAY_HINT 	"boolean"
set_parameter_property 	RUSER_EN		UNITS 			None
set_parameter_property 	RUSER_EN		VISIBLE		 	false
set_parameter_property 	RUSER_EN		HDL_PARAMETER 	false
set_parameter_property 	RUSER_EN		AFFECTS_GENERATION false
set_parameter_property  RUSER_EN		ENABLED  		true
set_parameter_property  RUSER_EN		GROUP  			"AXI bus signals for modification via conduit"
                        
add_parameter 		    RUSER_WIDTH		INTEGER 		5
set_parameter_property 	RUSER_WIDTH		ALLOWED_RANGES  1:32
set_parameter_property 	RUSER_WIDTH		DISPLAY_NAME	"RUSER Width"
set_parameter_property 	RUSER_WIDTH		TYPE 			INTEGER
set_parameter_property 	RUSER_WIDTH		UNITS 			None
set_parameter_property 	RUSER_WIDTH		VISIBLE		 	false
set_parameter_property 	RUSER_WIDTH		HDL_PARAMETER 	false
set_parameter_property 	RUSER_WIDTH		AFFECTS_GENERATION false
set_parameter_property  RUSER_WIDTH		ENABLED false
set_parameter_property  RUSER_WIDTH		GROUP  			"AXI bus signals for modification via conduit"

add_parameter 		    BUSER_EN		INTEGER 		0
set_parameter_property 	BUSER_EN		DISPLAY_NAME	"BUser Signals"
set_parameter_property 	BUSER_EN		DISPLAY_HINT 	"boolean"
set_parameter_property 	BUSER_EN		UNITS 			None
set_parameter_property 	BUSER_EN		VISIBLE		 	false
set_parameter_property 	BUSER_EN		HDL_PARAMETER 	false
set_parameter_property 	BUSER_EN		AFFECTS_GENERATION false
set_parameter_property  BUSER_EN		ENABLED  		true
set_parameter_property  BUSER_EN		GROUP  			"AXI bus signals for modification via conduit"
                        
add_parameter 		    BUSER_WIDTH		INTEGER 		5
set_parameter_property 	BUSER_WIDTH		ALLOWED_RANGES  1:32
set_parameter_property 	BUSER_WIDTH		DISPLAY_NAME	"BUSER Width"
set_parameter_property 	BUSER_WIDTH		TYPE 			INTEGER
set_parameter_property 	BUSER_WIDTH		UNITS 			None
set_parameter_property 	BUSER_WIDTH		VISIBLE		 	false
set_parameter_property 	BUSER_WIDTH		HDL_PARAMETER 	false
set_parameter_property 	BUSER_WIDTH		AFFECTS_GENERATION false
set_parameter_property  BUSER_WIDTH		ENABLED false
set_parameter_property  BUSER_WIDTH		GROUP  			"AXI bus signals for modification via conduit"

# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink rst_n reset_n Input 1



# 
# connection point altera_axi_master
# 
add_interface altera_axi_master axi start
set_interface_property altera_axi_master associatedClock clock
set_interface_property altera_axi_master associatedReset reset_sink
set_interface_property altera_axi_master readIssuingCapability 1
set_interface_property altera_axi_master writeIssuingCapability 1
set_interface_property altera_axi_master combinedIssuingCapability 1
set_interface_property altera_axi_master ENABLED true
set_interface_property altera_axi_master EXPORT_OF ""
set_interface_property altera_axi_master PORT_NAME_MAP ""
set_interface_property altera_axi_master CMSIS_SVD_VARIABLES ""
set_interface_property altera_axi_master SVD_ADDRESS_GROUP ""

add_interface_port altera_axi_master m_awvalid awvalid Output 1
add_interface_port altera_axi_master m_awlen awlen Output 4
add_interface_port altera_axi_master m_awsize awsize Output 3
add_interface_port altera_axi_master m_awburst awburst Output 2
add_interface_port altera_axi_master m_awlock awlock Output 2
add_interface_port altera_axi_master m_awcache awcache Output 4
add_interface_port altera_axi_master m_awprot awprot Output 3
add_interface_port altera_axi_master m_awready awready Input 1
add_interface_port altera_axi_master m_awuser awuser Output AXUSER_WIDTH
add_interface_port altera_axi_master m_arvalid arvalid Output 1
add_interface_port altera_axi_master m_arlen arlen Output 4
add_interface_port altera_axi_master m_arsize arsize Output 3
add_interface_port altera_axi_master m_arburst arburst Output 2
add_interface_port altera_axi_master m_arlock arlock Output 2
add_interface_port altera_axi_master m_arcache arcache Output 4
add_interface_port altera_axi_master m_arprot arprot Output 3
add_interface_port altera_axi_master m_arready arready Input 1
add_interface_port altera_axi_master m_aruser aruser Output AXUSER_WIDTH
add_interface_port altera_axi_master m_rvalid rvalid Input 1
add_interface_port altera_axi_master m_rlast rlast Input 1
add_interface_port altera_axi_master m_rresp rresp Input 2
add_interface_port altera_axi_master m_rready rready Output 1
add_interface_port altera_axi_master m_wvalid wvalid Output 1
add_interface_port altera_axi_master m_wlast wlast Output 1
add_interface_port altera_axi_master m_wready wready Input 1
add_interface_port altera_axi_master m_bvalid bvalid Input 1
add_interface_port altera_axi_master m_bresp bresp Input 2
add_interface_port altera_axi_master m_bready bready Output 1
add_interface_port altera_axi_master m_awaddr awaddr Output ADDRESS_WIDTH
add_interface_port altera_axi_master m_awid awid Output ID_WIDTH
add_interface_port altera_axi_master m_araddr araddr Output ADDRESS_WIDTH
add_interface_port altera_axi_master m_arid arid Output ID_WIDTH
add_interface_port altera_axi_master m_rdata rdata Input DATA_WIDTH
add_interface_port altera_axi_master m_rid rid Input ID_WIDTH
add_interface_port altera_axi_master m_wdata wdata Output DATA_WIDTH
add_interface_port altera_axi_master m_wstrb wstrb Output DATA_WIDTH/8
add_interface_port altera_axi_master m_wid wid Output ID_WIDTH
add_interface_port altera_axi_master m_bid bid Input ID_WIDTH


# 
# connection point altera_axi_slave
# 
add_interface altera_axi_slave axi end
set_interface_property altera_axi_slave associatedClock clock
set_interface_property altera_axi_slave associatedReset reset_sink
set_interface_property altera_axi_slave readAcceptanceCapability 1
set_interface_property altera_axi_slave writeAcceptanceCapability 1
set_interface_property altera_axi_slave combinedAcceptanceCapability 1
set_interface_property altera_axi_slave readDataReorderingDepth 1
set_interface_property altera_axi_slave bridgesToMaster ""
set_interface_property altera_axi_slave ENABLED true
set_interface_property altera_axi_slave EXPORT_OF ""
set_interface_property altera_axi_slave PORT_NAME_MAP ""
set_interface_property altera_axi_slave CMSIS_SVD_VARIABLES ""
set_interface_property altera_axi_slave SVD_ADDRESS_GROUP ""

add_interface_port altera_axi_slave s_awvalid awvalid Input 1
add_interface_port altera_axi_slave s_awlen awlen Input 4
add_interface_port altera_axi_slave s_awsize awsize Input 3
add_interface_port altera_axi_slave s_awburst awburst Input 2
add_interface_port altera_axi_slave s_awlock awlock Input 2
add_interface_port altera_axi_slave s_awcache awcache Input 4
add_interface_port altera_axi_slave s_awprot awprot Input 3
add_interface_port altera_axi_slave s_awready awready Output 1
add_interface_port altera_axi_slave s_awuser awuser Input AXUSER_WIDTH
add_interface_port altera_axi_slave s_arvalid arvalid Input 1
add_interface_port altera_axi_slave s_arlen arlen Input 4
add_interface_port altera_axi_slave s_arsize arsize Input 3
add_interface_port altera_axi_slave s_arburst arburst Input 2
add_interface_port altera_axi_slave s_arlock arlock Input 2
add_interface_port altera_axi_slave s_arcache arcache Input 4
add_interface_port altera_axi_slave s_arprot arprot Input 3
add_interface_port altera_axi_slave s_arready arready Output 1
add_interface_port altera_axi_slave s_aruser aruser Input AXUSER_WIDTH
add_interface_port altera_axi_slave s_rvalid rvalid Output 1
add_interface_port altera_axi_slave s_rlast rlast Output 1
add_interface_port altera_axi_slave s_rresp rresp Output 2
add_interface_port altera_axi_slave s_rready rready Input 1
add_interface_port altera_axi_slave s_wvalid wvalid Input 1
add_interface_port altera_axi_slave s_wlast wlast Input 1
add_interface_port altera_axi_slave s_wready wready Output 1
add_interface_port altera_axi_slave s_bvalid bvalid Output 1
add_interface_port altera_axi_slave s_bresp bresp Output 2
add_interface_port altera_axi_slave s_bready bready Input 1
add_interface_port altera_axi_slave s_awaddr awaddr Input ADDRESS_WIDTH
add_interface_port altera_axi_slave s_awid awid Input ID_WIDTH
add_interface_port altera_axi_slave s_araddr araddr Input ADDRESS_WIDTH
add_interface_port altera_axi_slave s_arid arid Input ID_WIDTH
add_interface_port altera_axi_slave s_rdata rdata Output DATA_WIDTH
add_interface_port altera_axi_slave s_rid rid Output ID_WIDTH
add_interface_port altera_axi_slave s_wdata wdata Input DATA_WIDTH
add_interface_port altera_axi_slave s_wstrb wstrb Input DATA_WIDTH/8
add_interface_port altera_axi_slave s_wid wid Input ID_WIDTH
add_interface_port altera_axi_slave s_bid bid Output ID_WIDTH

# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock clock
set_interface_property conduit_end associatedReset reset_sink
set_interface_property conduit_end ENABLED true
set_interface_property conduit_end EXPORT_OF ""
set_interface_property conduit_end PORT_NAME_MAP ""
set_interface_property conduit_end CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end SVD_ADDRESS_GROUP ""

add_interface_port conduit_end c_awcache export Input 4
add_interface_port conduit_end c_awprot export Input 3
add_interface_port conduit_end c_awuser export Input AXUSER_WIDTH
add_interface_port conduit_end c_arcache export Input 4
add_interface_port conduit_end c_aruser export Input AXUSER_WIDTH
add_interface_port conduit_end c_arprot export Input 3

proc elaborate {} {
  
  set ID_WIDTH   	[ get_parameter_value "ID_WIDTH" ]
  set ADDRESS_WIDTH [ get_parameter_value "ADDRESS_WIDTH" ]
  set AXCACHE_EN    [ get_parameter_value "AXCACHE_EN" ]
  set AXPROT_EN 	[ get_parameter_value "AXPROT_EN" ]
  set AXUSER_EN 	[ get_parameter_value "AXUSER_EN" ]
  set WUSER_EN 		[ get_parameter_value "WUSER_EN" ]
  set RUSER_EN 		[ get_parameter_value "RUSER_EN" ]
  set BUSER_EN 		[ get_parameter_value "BUSER_EN" ]
  set AXUSER_WIDTH 	[ get_parameter_value "AXUSER_WIDTH" ]
  set WUSER_WIDTH	[ get_parameter_value "WUSER_WIDTH" ]
  set RUSER_WIDTH	[ get_parameter_value "RUSER_WIDTH" ]
  set BUSER_WIDTH	[ get_parameter_value "BUSER_WIDTH" ]
  
  # puts "ADDRESS WIDTH is: ADDRESS_WIDTH"
}

proc validate {} {
  
  if { [get_parameter_value AXUSER_EN] == 1 } { 
      set_parameter_property AXUSER_WIDTH ENABLED true
  } else {
      set_parameter_property AXUSER_WIDTH ENABLED false
  }
    
  if { [get_parameter_value WUSER_EN] == 1 } { 
      set_parameter_property WUSER_WIDTH ENABLED true
  } else {
      set_parameter_property WUSER_WIDTH ENABLED false
  }
      
  if { [get_parameter_value RUSER_EN] == 1 } { 
      set_parameter_property RUSER_WIDTH ENABLED true
  } else {
      set_parameter_property RUSER_WIDTH ENABLED false
  }
        
  if { [get_parameter_value BUSER_EN] == 1 } { 
      set_parameter_property BUSER_WIDTH ENABLED true
  } else {
      set_parameter_property BUSER_WIDTH ENABLED false
  }
  
  
}